export default {
	3740382: {
		id: 3740382,
		userId: 190234,
		title: 'Empty item, high priority, private',
		completed: false,
		color: 0,
		colorValue: '#2AAEF5',
		category: 1,
		message: null,
		parent: 0,
		recurType: 0,
		recurInterval: 1,
		recurEndDate: '2019-03-06T07:03:13.346+02:00',
		timeLastUpdate: '2018-03-07T09:40:13.229+00:00',
		timeCreate: '2018-03-06T15:06:07.567+00:00',
		startDate: null,
		endDate: null,
		dueDate: null,
		dueDateActual: null,
		isAllDay: null,
		shared: true,
		reminderEnabled: null,
		reminderTime: null,
		reminderTimeType: null,
		starred: false,
		timeTrack: false,
		timeEst: 0,
		timeSpent: 0,
		priority: 30520,
		depth: null,
		lastCommentId: null,
		lastComment: null,
		lastCommentUserId: null,
		lastCommentCreateDate: null,
		lastInstanceDate: null,
		guid: '7fadbe48-07b5-444c-985d-66888932a92a',
		parentGuid: null,
		fileSize: null,
		assignee: 0,
		tags: null,
		version: 2,
		changed: null,
		instances: null,
		participants: null,
		mirror: null,
		publishURL: null,
		location: null,
		alerts: null,
		completeChangedCascade: null,
		share_changed_cascade: null,
		unread: null,
		shortName: null,
		issueId: null,
		permission: 100,
		adminPermission: null,
		permissions: [
			{
				level: 100,
				principal: '190234',
			},
		],
		parentTitle: null,
		parentProjectTitle: null,
		assigneeName: null,
		children: null,
		previews: null,
		lastTransitionTime: null,
		lastTransitionTimeFormat: null,
		lastTransitionUser: null,
		lastTransitionUserName: null,
	},
};
