// export const TestHierarchyStructure = { // sorted by priority
// 	id: 3234593,
// 	children: [{
// 		id: 3234592,
// 		children: [],
// 	}, {
// 		id: 3234591,
// 		children: [{
// 			id: 3234596,
// 			children: [],
// 		}],
// 	}],
// };

export default {
	3234591: {
		id: 3234591,
		title: 'second child item of level 1',
		completed: false,
		color: 0,
		category: 1,
		message: null,
		parent: 3234593,
		shared: true,
		starred: false,
		priority: 22122,
		depth: null,
		guid: '9010b0c9-1202-425a-a5e7-3bc26bef27ce',
		parentGuid: '9010b0c9-1102-425a-a6e7-3bc26bef27ce',
		assignee: 0,
		tags: null,
		version: 1,
		changed: null,
		instances: null,
		participants: null,
		mirror: null,
		location: null,
		alerts: null,
		share_changed_cascade: null,
		unread: null,
		permission: 100,
		adminPermission: null,
		permissions: [
			{
				level: 100,
				principal: 'f7621690-5619-42c8-a3ee-d1141c417f90',
			},
			{
				level: 100,
				principal: '190234',
			},
		],
		parentTitle: 'more tags',
		parentProjectTitle: null,
		assigneeName: null,
		children: null,
		previews: null,
		startDate: null,
		endDate: null,
		dueDate: null,
		dueDateActual: null,
		isAllDay: true,
		timeEst: 0,
		timeCreate: '2017-12-15T09:44:57.997+00:00',
		timeLastUpdate: '2017-12-15T09:44:58.024+00:00',
		timeSpent: 0,
		timeTrack: false,
		colorValue: '#2AAEF5',
		issueId: null,
		userId: 190234,
		shortName: null,
		completeChangedCascade: null,
		lastTransitionTime: null,
		lastTransitionTimeFormat: null,
		lastTransitionUser: null,
		lastTransitionUserName: null,
		lastInstanceDate: null,
		publishURL: null,
		fileSize: null,
		reminderEnabled: null,
		reminderTime: null,
		reminderTimeType: null,
		lastComment: null,
		lastCommentId: null,
		lastCommentUserId: null,
		lastCommentCreateDate: null,
		recurType: 0,
		recurInterval: 1,
		recurEndDate: null,
	},

	3234592: {
		id: 3234592,
		title: 'first child item of level 1',
		completed: false,
		color: 0,
		category: 1,
		message: null,
		parent: 3234593,
		shared: true,
		starred: false,
		priority: 22123,
		depth: null,
		guid: '9010b0c1-1102-425a-a5e7-3bc26bef27ce',
		parentGuid: '9010b0c9-1102-425a-a6e7-3bc26bef27ce',
		assignee: 0,
		tags: null,
		version: 1,
		changed: null,
		instances: null,
		participants: null,
		mirror: null,
		location: null,
		alerts: null,
		share_changed_cascade: null,
		unread: null,
		permission: 100,
		adminPermission: null,
		permissions: [
			{
				level: 100,
				principal: 'f7621690-5619-42c8-a3ee-d1141c417f90',
			},
			{
				level: 100,
				principal: '190234',
			},
		],
		parentTitle: 'more tags',
		parentProjectTitle: null,
		assigneeName: null,
		children: null,
		previews: null,
		startDate: null,
		endDate: null,
		dueDate: null,
		dueDateActual: null,
		isAllDay: true,
		timeEst: 0,
		timeCreate: '2017-12-15T09:44:57.997+00:00',
		timeLastUpdate: '2017-12-15T09:44:58.024+00:00',
		timeSpent: 0,
		timeTrack: false,
		colorValue: '#2AAEF5',
		issueId: null,
		userId: 190234,
		shortName: null,
		completeChangedCascade: null,
		lastTransitionTime: null,
		lastTransitionTimeFormat: null,
		lastTransitionUser: null,
		lastTransitionUserName: null,
		lastInstanceDate: null,
		publishURL: null,
		fileSize: null,
		reminderEnabled: null,
		reminderTime: null,
		reminderTimeType: null,
		lastComment: null,
		lastCommentId: null,
		lastCommentUserId: null,
		lastCommentCreateDate: null,
		recurType: 0,
		recurInterval: 1,
		recurEndDate: null,
	},

	3234593: {
		id: 3234593,
		title: 'parent item',
		completed: false,
		color: 0,
		category: 1,
		message: null,
		parent: null,
		shared: true,
		starred: false,
		priority: 22124,
		depth: null,
		guid: '9010b0c9-1102-425a-a6e7-3bc26bef27ce',
		parentGuid: null,
		assignee: 0,
		tags: null,
		version: 1,
		changed: null,
		instances: null,
		participants: null,
		mirror: null,
		location: null,
		alerts: null,
		share_changed_cascade: null,
		unread: null,
		permission: 100,
		adminPermission: null,
		permissions: [
			{
				level: 100,
				principal: 'f7621690-5619-42c8-a3ee-d1141c417f90',
			},
			{
				level: 100,
				principal: '190234',
			},
		],
		parentTitle: 'more tags',
		parentProjectTitle: null,
		assigneeName: null,
		children: null,
		previews: null,
		startDate: null,
		endDate: null,
		dueDate: null,
		dueDateActual: null,
		isAllDay: true,
		timeEst: 0,
		timeCreate: '2017-12-15T09:44:57.997+00:00',
		timeLastUpdate: '2017-12-15T09:44:58.024+00:00',
		timeSpent: 0,
		timeTrack: false,
		colorValue: '#2AAEF5',
		issueId: null,
		userId: 190234,
		shortName: null,
		completeChangedCascade: null,
		lastTransitionTime: null,
		lastTransitionTimeFormat: null,
		lastTransitionUser: null,
		lastTransitionUserName: null,
		lastInstanceDate: null,
		publishURL: null,
		fileSize: null,
		reminderEnabled: null,
		reminderTime: null,
		reminderTimeType: null,
		lastComment: null,
		lastCommentId: null,
		lastCommentUserId: null,
		lastCommentCreateDate: null,
		recurType: 0,
		recurInterval: 1,
		recurEndDate: null,
	},

	3234596: {
		id: 3234596,
		title: 'first child item of level 2',
		completed: false,
		color: 0,
		category: 1,
		message: null,
		parent: 3234591,
		shared: true,
		starred: false,
		priority: 22120,
		depth: null,
		guid: '9110b0c9-1202-425a-a5e7-3bc26bef27ce',
		parentGuid: '9010b0c9-1202-425a-a5e7-3bc26bef27ce',
		assignee: 0,
		tags: null,
		version: 1,
		changed: null,
		instances: null,
		participants: null,
		mirror: null,
		location: null,
		alerts: null,
		share_changed_cascade: null,
		unread: null,
		permission: 100,
		adminPermission: null,
		permissions: [
			{
				level: 100,
				principal: 'f7621690-5619-42c8-a3ee-d1141c417f90',
			},
			{
				level: 100,
				principal: '190234',
			},
		],
		parentTitle: 'more tags',
		parentProjectTitle: null,
		assigneeName: null,
		children: null,
		previews: null,
		startDate: null,
		endDate: null,
		dueDate: null,
		dueDateActual: null,
		isAllDay: true,
		timeEst: 0,
		timeCreate: '2017-12-15T09:44:57.997+00:00',
		timeLastUpdate: '2017-12-15T09:44:58.024+00:00',
		timeSpent: 0,
		timeTrack: false,
		colorValue: '#2AAEF5',
		issueId: null,
		userId: 190234,
		shortName: null,
		completeChangedCascade: null,
		lastTransitionTime: null,
		lastTransitionTimeFormat: null,
		lastTransitionUser: null,
		lastTransitionUserName: null,
		lastInstanceDate: null,
		publishURL: null,
		fileSize: null,
		reminderEnabled: null,
		reminderTime: null,
		reminderTimeType: null,
		lastComment: null,
		lastCommentId: null,
		lastCommentUserId: null,
		lastCommentCreateDate: null,
		recurType: 0,
		recurInterval: 1,
		recurEndDate: null,
	},
};
